version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: install test dependencies
          command: |
            go get github.com/mattn/goveralls
            go get golang.org/x/tools/cmd/cover
      - run:
          name: unit test
          command: COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN GO111MODULE=on go test -v -covermode=count -coverprofile=coverage.out ./feed
      - run:
          name: install node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: install serverless
          command: 'sudo npm install -g serverless'
      - deploy:
          name: deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make deployprod
              else
                make deploy
              fi