version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: install lint tool
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - run:
          name: golangci-lint
          command: golangci-lint run
      - run:
          name: install test dependencies
          command: |
            go get github.com/mattn/goveralls
            go get golang.org/x/tools/cmd/cover
      - run:
          name: unit test
          command: GO111MODULE=on go test -v -covermode=count -coverprofile=coverage.out ./feed
      - run:
          name: upload coverage
          command: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_REPO_TOKEN
  deploy:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: install node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: install serverless
          command: 'sudo npm install -g serverless'
      - deploy:
          name: deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make deployprod
              else
                make deploy
              fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          context: aws-serverless
